version: '3.4'

services:
  estms-db:
    image: postgres:latest
    container_name: estms-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=estms
    ports:
      - "5433:5432"
    restart: always